# Generated by Django 3.2 on 2021-08-27 13:25

import casting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=casting.models.save_course_image, verbose_name='Subject Image')),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('capacity', models.IntegerField(max_length=200)),
                ('pcs', models.IntegerField(max_length=200)),
                ('projector', models.BooleanField(default=True)),
                ('ac', models.BooleanField(default=True)),
                ('room_type', models.CharField(choices=[('lab', 'lab'), ('class', 'class'), ('meeting', 'meeting')], default='class', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_type',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('None_Engineering', 'None_Engineering')], default='Engineering', max_length=100),
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_tt_days', to='casting.days')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_tt_slots', to='casting.slots')),
                ('slot_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_tt_room', to='casting.room')),
                ('slot_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_tt_section', to='casting.section')),
                ('slot_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_tt_course', to='casting.course')),
            ],
        ),
        migrations.CreateModel(
            name='freetimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ft_days', to='casting.days')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ft_slots', to='casting.slots')),
                ('slot_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ft_room', to='casting.room')),
            ],
        ),
    ]
