# Generated by Django 3.2 on 2021-08-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0002_auto_20210827_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freetimetable',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slots',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
