# Generated by Django 3.2 on 2021-09-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0004_auto_20210902_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sem',
        ),
    ]
