# Generated by Django 3.2 on 2021-09-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0005_auto_20210906_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slotslab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=45, max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='pcs',
            field=models.IntegerField(default=2, max_length=200),
        ),
        migrations.CreateModel(
            name='timetablelab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ttl_days', to='casting.days')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ttl_slots', to='casting.slotslab')),
                ('slot_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ttl_room', to='casting.room')),
                ('slot_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ttl_section', to='casting.section')),
                ('slot_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ttl_course', to='casting.course')),
            ],
        ),
        migrations.CreateModel(
            name='freetimetablelab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ftl_days', to='casting.days')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ftl_slots', to='casting.slotslab')),
                ('slot_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_ftl_room', to='casting.room')),
            ],
        ),
    ]
