# Generated by Django 3.2 on 2021-09-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0006_auto_20210907_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='sec_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('couid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cou_sec', to='casting.course')),
                ('secid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_cou', to='casting.section')),
            ],
        ),
    ]
