# Generated by Django 3.2 on 2021-09-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0008_pro_room_projector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projector',
            name='capacity_run',
        ),
        migrations.RemoveField(
            model_name='projector',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projector',
            name='image',
        ),
        migrations.AddField(
            model_name='projector',
            name='capacity',
            field=models.IntegerField(default=200, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projector',
            name='t_run',
            field=models.IntegerField(default=100, max_length=40),
            preserve_default=False,
        ),
    ]
