# Generated by Django 3.2 on 2021-11-15 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0009_auto_20210915_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='oberecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('year', models.CharField(max_length=40)),
                ('enrolled', models.IntegerField(default=100)),
                ('clo1', models.IntegerField(default=100)),
                ('clo2', models.IntegerField(default=100)),
                ('clo3', models.IntegerField(default=100)),
                ('clo4', models.IntegerField(default=100)),
                ('cloall', models.IntegerField(default=100)),
                ('passed', models.IntegerField(default=100)),
                ('failed', models.IntegerField(default=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_cou', to='casting.course')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_dept', to='casting.department')),
            ],
        ),
    ]
