# Generated by Django 3.2 on 2021-12-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0010_oberecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='twc',
            field=models.IntegerField(default=45, max_length=200),
        ),
    ]
