# Generated by Django 3.2 on 2021-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0014_alter_projector_t_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='projector',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
